# Generated by Django 2.2.5 on 2020-12-12 08:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('named', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='标签名称')),
                ('color', models.CharField(blank=True, default='#CCD6D5', max_length=20, null=True, unique=True, verbose_name='标签名字')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
            },
        ),
        migrations.CreateModel(
            name='Freight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(blank=True, max_length=80, null=True, verbose_name='菜品编号')),
                ('named', models.CharField(blank=True, max_length=80, null=True, verbose_name='菜品名称')),
                ('unit', models.SmallIntegerField(choices=[(0, '斤'), (1, '包'), (2, '件'), (3, '扎'), (4, '两'), (5, '磅')], default=1, null=True, verbose_name='单位')),
                ('price', models.CharField(default='0.00', max_length=90, verbose_name='默认单价')),
                ('status', models.BooleanField(default=True, verbose_name='数据状态')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='創建時間')),
                ('tag', models.ManyToManyField(blank=True, related_name='tag', to='freight.Tag', verbose_name='标签')),
            ],
            options={
                'verbose_name': '菜品',
                'verbose_name_plural': '菜品',
            },
        ),
    ]
