# Generated by Django 2.2.5 on 2020-11-30 13:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Freight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(blank=True, max_length=80, null=True, verbose_name='菜品编号')),
                ('named', models.CharField(blank=True, max_length=80, null=True, verbose_name='菜品名称')),
                ('unit', models.SmallIntegerField(choices=[(0, '斤'), (1, '包'), (2, '件'), (3, '扎'), (4, '两'), (5, '磅')], default=1, null=True, verbose_name='单位')),
                ('status', models.BooleanField(default=True, verbose_name='数据状态')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='創建時間')),
            ],
            options={
                'verbose_name': '菜品',
                'verbose_name_plural': '菜品',
            },
        ),
        migrations.CreateModel(
            name='FreightEveryMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.CharField(max_length=90, verbose_name='折扣价格')),
                ('price', models.CharField(max_length=90, verbose_name='对应单价')),
                ('status', models.BooleanField(default=True, verbose_name='数据状态')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='創建時間')),
                ('freight', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='freight.Freight', verbose_name='所属菜品')),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='member.Member', verbose_name='所属客人')),
            ],
            options={
                'verbose_name': '客人菜品对应单价',
                'verbose_name_plural': '客人菜品对应单价',
            },
        ),
    ]
