# Generated by Django 2.2.5 on 2020-12-01 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freight', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freighteverymember',
            name='discount',
            field=models.CharField(blank=True, max_length=90, null=True, verbose_name='折扣价格'),
        ),
    ]
