# Generated by Django 2.2.5 on 2021-08-23 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freight', '0003_auto_20210106_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='status',
            field=models.BooleanField(default=True, verbose_name='数据状态'),
        ),
    ]
