# Generated by Django 2.2.5 on 2020-12-05 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freight', '0003_auto_20201201_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='freight',
            name='price',
            field=models.CharField(default='0.00', max_length=90, verbose_name='对应单价'),
        ),
        migrations.DeleteModel(
            name='FreightEveryMember',
        ),
    ]
