# Generated by Django 2.2.5 on 2021-03-19 12:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='now_login',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='本次登录'),
        ),
    ]
