# Generated by Django 2.2.5 on 2020-12-05 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'verbose_name': '报价清单', 'verbose_name_plural': '报价清单'},
        ),
    ]
