# Generated by Django 2.2.5 on 2020-12-14 08:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='content',
        ),
        migrations.AlterField(
            model_name='listing',
            name='merge_status',
            field=models.BooleanField(default=False, verbose_name='是否合并过'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='pay_status',
            field=models.BooleanField(default=False, verbose_name='是否支付过'),
        ),
        migrations.CreateModel(
            name='ListingContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, default='--', max_length=7200, null=True, verbose_name='发票内容')),
                ('status', models.BooleanField(default=True, verbose_name='数据状态')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='創建時間')),
                ('listing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='listing.Listing', verbose_name='所属发票')),
            ],
            options={
                'verbose_name': '发票内容',
                'verbose_name_plural': '发票内容',
            },
        ),
    ]
