# Generated by Django 2.2.5 on 2020-12-18 11:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_auto_20201214_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='freight_item_num',
            field=models.SmallIntegerField(default=0, null=True, verbose_name='购菜项数'),
        ),
        migrations.AddField(
            model_name='listing',
            name='pdf_status',
            field=models.BooleanField(default=False, verbose_name='是否导出过'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='draft_status',
            field=models.BooleanField(default=False, verbose_name='是否是草稿'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listing_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='报价日期'),
        ),
    ]
