# Generated by Django 2.2.5 on 2021-01-06 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0003_auto_20201218_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='pay_way',
            field=models.SmallIntegerField(choices=[(0, '支票'), (1, '现金')], default=1, null=True, verbose_name='付款方式'),
        ),
    ]
