# Generated by Django 2.2.5 on 2021-01-06 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0004_auto_20210106_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='pay_contact_area',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='销售员电话号码前缀'),
        ),
    ]
