# Generated by Django 2.2.5 on 2021-03-17 08:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0005_listing_pay_contact_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingNo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('val', models.CharField(blank=True, max_length=150, null=True, verbose_name='具体值')),
                ('used', models.BooleanField(default=True, verbose_name='是否使用默认编号')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='創建時間')),
            ],
            options={
                'verbose_name': '发票编号记录',
                'verbose_name_plural': '发票编号记录',
            },
        ),
        migrations.AlterField(
            model_name='listing',
            name='num',
            field=models.CharField(blank=True, default='001', max_length=150, null=True, verbose_name='发票编号'),
        ),
        migrations.AlterField(
            model_name='listingcontent',
            name='content',
            field=models.TextField(blank=True, default='--', max_length=52000, null=True, verbose_name='发票内容'),
        ),
    ]
