# Generated by Django 2.2.5 on 2021-03-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0006_auto_20210317_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingno',
            name='listing_id',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='所属发票 ID'),
        ),
    ]
