# Generated by Django 2.2.5 on 2021-03-17 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0007_listingno_listing_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingno',
            name='status',
            field=models.BooleanField(default=True, verbose_name='数据状态'),
        ),
    ]
