# Generated by Django 2.2.5 on 2020-12-12 08:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('freight', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=30, null=True, verbose_name='手机号码前缀')),
            ],
            options={
                'verbose_name': '地域与电话号码前缀',
                'verbose_name_plural': '地域与电话号码前缀',
            },
        ),
        migrations.CreateModel(
            name='Membery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(blank=True, max_length=80, null=True, verbose_name='客户编号')),
                ('named', models.CharField(blank=True, max_length=80, null=True, verbose_name='公司名称')),
                ('phoned', models.CharField(blank=True, max_length=60, null=True, verbose_name='电话')),
                ('email', models.CharField(blank=True, max_length=200, null=True, verbose_name='邮箱地址')),
                ('addr', models.CharField(blank=True, max_length=150, null=True, verbose_name='送货地址')),
                ('status', models.BooleanField(default=True, verbose_name='数据状态')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='創建時間')),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='member.Area', verbose_name='手机号码前缀')),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='freight.Tag', verbose_name='标签')),
            ],
            options={
                'verbose_name': '客人',
                'verbose_name_plural': '客人',
            },
        ),
        migrations.CreateModel(
            name='PriceCollect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(blank=True, max_length=80, null=True, verbose_name='报价单号')),
                ('content', models.TextField(blank=True, default='--', max_length=7200, null=True, verbose_name='清单内容')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='起始时间')),
                ('end_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='结束时间')),
                ('draft_status', models.BooleanField(default=True, verbose_name='是否是草稿')),
                ('over_status', models.BooleanField(default=True, verbose_name='是否完结')),
                ('first_pdf', models.BooleanField(default=True, verbose_name='是否导出过 Pdf')),
                ('status', models.BooleanField(default=True, verbose_name='数据状态')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='創建時間')),
                ('membery', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='member.Membery', verbose_name='所属客人')),
            ],
            options={
                'verbose_name': '报价单',
                'verbose_name_plural': '报价单',
            },
        ),
    ]
