# Generated by Django 2.2.5 on 2020-12-11 08:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=30, null=True, verbose_name='手机号码前缀')),
            ],
            options={
                'verbose_name': '地域与电话号码前缀',
                'verbose_name_plural': '地域与电话号码前缀',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(blank=True, max_length=80, null=True, verbose_name='客户编号')),
                ('named', models.CharField(blank=True, max_length=80, null=True, verbose_name='公司名称')),
                ('phoned', models.CharField(blank=True, max_length=60, null=True, verbose_name='电话')),
                ('email', models.CharField(blank=True, max_length=200, null=True, verbose_name='邮箱地址')),
                ('addr', models.CharField(blank=True, max_length=150, null=True, verbose_name='送货地址')),
                ('status', models.BooleanField(default=True, verbose_name='数据状态')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='創建時間')),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='member.Area', verbose_name='手机号码前缀')),
            ],
            options={
                'verbose_name': '客人',
                'verbose_name_plural': '客人',
            },
        ),
    ]
