# Generated by Django 2.2.5 on 2020-12-18 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20201214_1617'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricecollectcontent',
            options={'verbose_name': '报价单内容', 'verbose_name_plural': '报价单内容'},
        ),
        migrations.AddField(
            model_name='membery',
            name='contact_named',
            field=models.CharField(blank=True, default='无', max_length=60, null=True, verbose_name='联络人姓名'),
        ),
    ]
