# Generated by Django 2.2.5 on 2020-12-23 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_auto_20201223_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricecollect',
            name='end_time',
            field=models.DateField(blank=True, null=True, verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='pricecollect',
            name='start_time',
            field=models.DateField(blank=True, null=True, verbose_name='起始时间'),
        ),
    ]
