# Generated by Django 2.2.5 on 2020-12-23 08:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_auto_20201223_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricecollect',
            name='end_time',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='pricecollect',
            name='start_time',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='起始时间'),
        ),
    ]
