# Generated by Django 2.2.5 on 2021-01-06 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0007_auto_20201223_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricecollectcontent',
            name='content',
            field=models.TextField(blank=True, default='--', max_length=9200, null=True, verbose_name='清单内容'),
        ),
    ]
