# Generated by Django 2.2.5 on 2021-03-17 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0008_auto_20210106_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricecollectcontent',
            name='content',
            field=models.TextField(blank=True, default='--', max_length=52000, null=True, verbose_name='清单内容'),
        ),
    ]
