# Generated by Django 2.2.5 on 2021-03-19 08:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0009_auto_20210317_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_time', models.SmallIntegerField(choices=[(0, '即付'), (1, '月結'), (2, '月結30日'), (3, '月結45日'), (4, '月結60日')], default=0, null=True, verbose_name='付款期限')),
                ('status', models.BooleanField(default=True, verbose_name='数据状态')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='創建時間')),
            ],
            options={
                'verbose_name': '付款日期',
                'verbose_name_plural': '付款日期',
            },
        ),
        migrations.AddField(
            model_name='membery',
            name='pay_time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='member.PayTime', verbose_name='付款日期'),
        ),
        migrations.AddField(
            model_name='pricecollect',
            name='pay_time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='member.PayTime', verbose_name='付款日期'),
        ),
    ]
