# Generated by Django 2.2.5 on 2021-03-19 09:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0010_auto_20210319_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='paytime',
            name='named',
            field=models.CharField(max_length=30, null=True, verbose_name='期限名称'),
        ),
        migrations.AlterField(
            model_name='pricecollect',
            name='end_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='备用时间'),
        ),
        migrations.AlterField(
            model_name='pricecollect',
            name='over_status',
            field=models.BooleanField(default=False, verbose_name='完结付款？'),
        ),
        migrations.AlterField(
            model_name='pricecollect',
            name='start_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='发票时间'),
        ),
    ]
