# Generated by Django 2.2.5 on 2021-03-23 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0011_auto_20210319_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='membery',
            name='pay_way',
            field=models.SmallIntegerField(choices=[(0, '支票'), (1, '现金')], default=1, null=True, verbose_name='付款方式'),
        ),
    ]
